# Generated by Django 6.0.2 on 2026-02-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('footer_bio_ne', models.TextField(blank=True)),
                ('footer_bio_en', models.TextField(blank=True)),
                ('footer_bio_de', models.TextField(blank=True)),
                ('quick_links_title_ne', models.CharField(default='Quick Links', max_length=100)),
                ('quick_links_title_en', models.CharField(default='Quick Links', max_length=100)),
                ('quick_links_title_de', models.CharField(default='Quick Links', max_length=100)),
                ('contact_info_title_ne', models.CharField(default='Contact Us', max_length=100)),
                ('contact_info_title_en', models.CharField(default='Contact Us', max_length=100)),
                ('contact_info_title_de', models.CharField(default='Kontakt', max_length=100)),
                ('membership_title_ne', models.CharField(default='Membership', max_length=100)),
                ('membership_title_en', models.CharField(default='Membership', max_length=100)),
                ('membership_title_de', models.CharField(default='Mitgliedschaft', max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('registered_info', models.CharField(max_length=100)),
                ('cta_label_ne', models.CharField(blank=True, max_length=100)),
                ('cta_label_en', models.CharField(blank=True, max_length=100)),
                ('cta_label_de', models.CharField(blank=True, max_length=100)),
                ('cta_btn_text_ne', models.CharField(blank=True, max_length=50)),
                ('cta_btn_text_en', models.CharField(blank=True, max_length=50)),
                ('cta_btn_text_de', models.CharField(blank=True, max_length=50)),
                ('cta_link', models.CharField(blank=True, max_length=200)),
                ('copyright_text_ne', models.CharField(help_text='Use [year] placeholder', max_length=200)),
                ('copyright_text_en', models.CharField(help_text='Use [year] placeholder', max_length=200)),
                ('copyright_text_de', models.CharField(help_text='Use [year] placeholder', max_length=200)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('href', models.CharField(max_length=200)),
                ('label_ne', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('label_de', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media')),
            ],
            options={
                'verbose_name': 'Navigation Settings',
                'verbose_name_plural': 'Navigation Settings',
            },
        ),
    ]
