# Generated by Django 6.0.2 on 2026-02-16 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='cta_btn_text_de',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='cta_btn_text_en',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='cta_btn_text_ne',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='cta_label_de',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='cta_label_en',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='cta_label_ne',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='footer_bio_de',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='footer_bio_en',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='footer_bio_ne',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='membership_title_de',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='membership_title_en',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='membership_title_ne',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='address_de',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='address_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='address_ne',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='brand_name_main',
            field=models.CharField(default='Nepal Volleyball Club', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='brand_name_secondary',
            field=models.CharField(default='Hamburg e.V.', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Description (DE)'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='description_ne',
            field=models.TextField(blank=True, verbose_name='Description (NE)'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_logo', to='media.media'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_btn_text_de',
            field=models.CharField(default='Abonnieren', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_btn_text_en',
            field=models.CharField(default='Subscribe', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_btn_text_ne',
            field=models.CharField(default='Subscribe', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_desc_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_desc_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_desc_ne',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_title_de',
            field=models.CharField(default='Newsletter', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_title_en',
            field=models.CharField(default='Newsletter', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_title_ne',
            field=models.CharField(default='Newsletter', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='privacy_label_de',
            field=models.CharField(default='Datenschutz', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='privacy_label_en',
            field=models.CharField(default='Privacy Policy', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='privacy_label_ne',
            field=models.CharField(default='Privacy Policy', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='terms_label_de',
            field=models.CharField(default='AGB', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='terms_label_en',
            field=models.CharField(default='Terms of Service', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='terms_label_ne',
            field=models.CharField(default='Terms of Service', max_length=100),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='brand_name_main_de',
            field=models.CharField(default='Nepal Volleyball Club', max_length=100),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='brand_name_main_en',
            field=models.CharField(default='Nepal Volleyball Club', max_length=100),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='brand_name_main_ne',
            field=models.CharField(default='Nepal Volleyball Club', max_length=100),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='brand_name_secondary_de',
            field=models.CharField(default='Hamburg e.V.', max_length=100),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='brand_name_secondary_en',
            field=models.CharField(default='Hamburg e.V.', max_length=100),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='brand_name_secondary_ne',
            field=models.CharField(default='Hamburg e.V.', max_length=100),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='registered_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media'),
        ),
    ]
