# Generated by Django 6.0.2 on 2026-02-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_remove_footersettings_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='brand_name_main',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='brand_name_secondary',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='brand_name_main_de',
            field=models.CharField(default='Nepal Volleyball Club', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='brand_name_main_en',
            field=models.CharField(default='Nepal Volleyball Club', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='brand_name_main_ne',
            field=models.CharField(default='Nepal Volleyball Club', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='brand_name_secondary_de',
            field=models.CharField(default='Hamburg e.V.', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='brand_name_secondary_en',
            field=models.CharField(default='Hamburg e.V.', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='brand_name_secondary_ne',
            field=models.CharField(default='Hamburg e.V.', max_length=100),
        ),
    ]
