# Generated by Django 6.0.2 on 2026-02-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_remove_footersettings_brand_name_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/footer/'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/navbar/'),
        ),
    ]
