# Generated by Django 6.0.2 on 2026-02-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_alter_footersettings_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersettings',
            old_name='newsletter_desc_de',
            new_name='membership_description_de',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='newsletter_desc_en',
            new_name='membership_description_en',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='newsletter_desc_ne',
            new_name='membership_description_ne',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_btn_text_de',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_btn_text_en',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_btn_text_ne',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_title_de',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_title_en',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='newsletter_title_ne',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='membership_button_text_de',
            field=models.CharField(default='Jetzt beitreten', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='membership_button_text_en',
            field=models.CharField(default='Join Now', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='membership_button_text_ne',
            field=models.CharField(default='Join Now', max_length=50),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='membership_title_de',
            field=models.CharField(default='Mitgliedschaft', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='membership_title_en',
            field=models.CharField(default='Membership', max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='membership_title_ne',
            field=models.CharField(default='Membership', max_length=100),
        ),
    ]
