# Generated by Django 6.0.2 on 2026-02-16 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_rename_newsletter_desc_de_footersettings_membership_description_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ne', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('label_de', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='navigation.footersettings')),
            ],
            options={
                'verbose_name': 'Footer Quick Link',
                'verbose_name_plural': 'Footer Quick Links',
                'ordering': ['order'],
            },
        ),
    ]
