# Generated by Django 6.0.2 on 2026-02-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategoriesProxy',
            fields=[
            ],
            options={
                'verbose_name': '03: Categories',
                'verbose_name_plural': '03: Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery_options.gallerycategory',),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'Gallery Page',
                'verbose_name_plural': 'Gallery Pages',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/gallery/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL (CDN)')),
                ('title_ne', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_de', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='gallery_options.gallerycategory')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery_options.gallerypage')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Hero Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Hero Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Hero Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Hero Text (NE)')),
                ('text_en', models.TextField(verbose_name='Hero Text (EN)')),
                ('text_de', models.TextField(verbose_name='Hero Text (DE)')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='gallery_options.gallerypage')),
            ],
            options={
                'verbose_name': 'Gallery Hero',
            },
        ),
        migrations.CreateModel(
            name='GalleryHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': '02: Hero Section',
                'verbose_name_plural': '02: Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery_options.gallerypage',),
        ),
        migrations.CreateModel(
            name='GalleryImagesProxy',
            fields=[
            ],
            options={
                'verbose_name': '04: Gallery Images',
                'verbose_name_plural': '04: Gallery Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery_options.gallerypage',),
        ),
        migrations.CreateModel(
            name='GalleryLabelsProxy',
            fields=[
            ],
            options={
                'verbose_name': '05: Labels & Settings',
                'verbose_name_plural': '05: Labels & Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery_options.gallerypage',),
        ),
        migrations.CreateModel(
            name='GalleryPageProxy',
            fields=[
            ],
            options={
                'verbose_name': '01: Main Settings',
                'verbose_name_plural': '01: Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery_options.gallerypage',),
        ),
        migrations.CreateModel(
            name='GallerySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_images_text_ne', models.CharField(default='यो श्रेणीमा कुनै तस्बिर छैन।', max_length=200)),
                ('no_images_text_en', models.CharField(default='No photos in this category.', max_length=200)),
                ('no_images_text_de', models.CharField(default='Keine Fotos in dieser Kategorie.', max_length=200)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='gallery_options.gallerypage')),
            ],
            options={
                'verbose_name': 'Gallery Labels & Settings',
            },
        ),
    ]
