# Generated by Django 6.0.2 on 2026-02-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Pages',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Lucide icon name (e.g. MapPin, Phone, Mail)', max_length=50)),
                ('label_ne', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('label_de', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='contact_options.contactpage')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/contact/hero/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Hero Image URL (CDN)')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Hero Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Hero Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Hero Title (DE)')),
                ('subtitle_ne', models.CharField(max_length=200, verbose_name='Hero Subtitle (NE)')),
                ('subtitle_en', models.CharField(max_length=200, verbose_name='Hero Subtitle (EN)')),
                ('subtitle_de', models.CharField(max_length=200, verbose_name='Hero Subtitle (DE)')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='contact_options.contactpage')),
            ],
            options={
                'verbose_name': 'Contact Hero',
            },
        ),
        migrations.CreateModel(
            name='ContactHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': '02: Hero Section',
                'verbose_name_plural': '02: Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contact_options.contactpage',),
        ),
        migrations.CreateModel(
            name='ContactInfoProxy',
            fields=[
            ],
            options={
                'verbose_name': '03: Contact Methods',
                'verbose_name_plural': '03: Contact Methods',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contact_options.contactpage',),
        ),
        migrations.CreateModel(
            name='ContactLabelsProxy',
            fields=[
            ],
            options={
                'verbose_name': '05: Labels & Settings',
                'verbose_name_plural': '05: Labels & Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contact_options.contactpage',),
        ),
        migrations.CreateModel(
            name='ContactPageProxy',
            fields=[
            ],
            options={
                'verbose_name': '01: Main Settings',
                'verbose_name_plural': '01: Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contact_options.contactpage',),
        ),
        migrations.CreateModel(
            name='ContactSocialProxy',
            fields=[
            ],
            options={
                'verbose_name': '04: Social Links',
                'verbose_name_plural': '04: Social Links',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contact_options.contactpage',),
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title_ne', models.CharField(default='सन्देश पठाउनुहोस्', max_length=200)),
                ('form_title_en', models.CharField(default='Send Message', max_length=200)),
                ('form_title_de', models.CharField(default='Nachricht senden', max_length=200)),
                ('label_name_ne', models.CharField(default='नाम', max_length=100)),
                ('label_name_en', models.CharField(default='Name', max_length=100)),
                ('label_name_de', models.CharField(default='Name', max_length=100)),
                ('label_email_ne', models.CharField(default='इमेल', max_length=100)),
                ('label_email_en', models.CharField(default='Email', max_length=100)),
                ('label_email_de', models.CharField(default='E-Mail', max_length=100)),
                ('label_subject_ne', models.CharField(default='विषय', max_length=100)),
                ('label_subject_en', models.CharField(default='Subject', max_length=100)),
                ('label_subject_de', models.CharField(default='Betreff', max_length=100)),
                ('label_message_ne', models.CharField(default='सन्देश', max_length=100)),
                ('label_message_en', models.CharField(default='Message', max_length=100)),
                ('label_message_de', models.CharField(default='Nachricht', max_length=100)),
                ('label_submit_ne', models.CharField(default='पठाउनुहोस्', max_length=100)),
                ('label_submit_en', models.CharField(default='Send', max_length=100)),
                ('label_submit_de', models.CharField(default='Senden', max_length=100)),
                ('info_section_title_ne', models.CharField(default='सम्पर्क जानकारी', max_length=200)),
                ('info_section_title_en', models.CharField(default='Contact Information', max_length=200)),
                ('info_section_title_de', models.CharField(default='Kontaktinformationen', max_length=200)),
                ('social_section_title_ne', models.CharField(default='सामाजिक सञ्जाल', max_length=200)),
                ('social_section_title_en', models.CharField(default='Social Media', max_length=200)),
                ('social_section_title_de', models.CharField(default='Soziale Medien', max_length=200)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='contact_options.contactpage')),
            ],
            options={
                'verbose_name': 'Contact Labels & Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(help_text='Lucide icon name (e.g. Facebook, Instagram, Twitter)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='contact_options.contactpage')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order'],
            },
        ),
    ]
