# Generated by Django 6.0.2 on 2026-02-16 10:25

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title_ne', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_de', models.CharField(max_length=200)),
                ('content_ne', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField()),
                ('content_de', ckeditor.fields.RichTextField()),
                ('category_ne', models.CharField(blank=True, max_length=100)),
                ('category_en', models.CharField(blank=True, max_length=100)),
                ('category_de', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title_ne', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_de', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt_ne', models.TextField()),
                ('excerpt_en', models.TextField()),
                ('excerpt_de', models.TextField()),
                ('content_ne', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField()),
                ('content_de', ckeditor.fields.RichTextField()),
                ('category_ne', models.CharField(max_length=100)),
                ('category_en', models.CharField(max_length=100)),
                ('category_de', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title_ne', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_de', models.CharField(max_length=200)),
                ('description_ne', ckeditor.fields.RichTextField()),
                ('description_en', ckeditor.fields.RichTextField()),
                ('description_de', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('event_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title_ne', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_de', models.CharField(blank=True, max_length=200)),
                ('category_ne', models.CharField(max_length=100)),
                ('category_en', models.CharField(max_length=100)),
                ('category_de', models.CharField(max_length=100)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('member_type', models.CharField(choices=[('executive', 'Executive Committee'), ('general', 'General Member'), ('coach', 'Coach'), ('player', 'Player')], max_length=20)),
                ('role_ne', models.CharField(blank=True, max_length=100)),
                ('role_en', models.CharField(blank=True, max_length=100)),
                ('role_de', models.CharField(blank=True, max_length=100)),
                ('bio_ne', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_de', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('position_ne', models.CharField(blank=True, max_length=100)),
                ('position_en', models.CharField(blank=True, max_length=100)),
                ('position_de', models.CharField(blank=True, max_length=100)),
                ('experience_ne', models.CharField(blank=True, max_length=100)),
                ('experience_en', models.CharField(blank=True, max_length=100)),
                ('experience_de', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
