# Generated by Django 6.0.2 on 2026-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name_ne', models.CharField(default='Nepal Volleyball Club', max_length=200)),
                ('brand_name_en', models.CharField(default='Nepal Volleyball Club', max_length=200)),
                ('brand_name_de', models.CharField(default='Nepal Volleyball Club', max_length=200)),
                ('brand_subtitle_ne', models.CharField(default='Hamburg e.V.', max_length=200)),
                ('brand_subtitle_en', models.CharField(default='Hamburg e.V.', max_length=200)),
                ('brand_subtitle_de', models.CharField(default='Hamburg e.V.', max_length=200)),
                ('primary_500', models.CharField(default='#DC143C', help_text='Main Crimson', max_length=7)),
                ('primary_600', models.CharField(default='#B01030', help_text='Hover Crimson', max_length=7)),
                ('secondary_500', models.CharField(default='#003893', help_text='Main Blue', max_length=7)),
                ('accent_500', models.CharField(default='#FFD700', help_text='Gold', max_length=7)),
                ('enable_nepal_pattern', models.BooleanField(default=True)),
                ('enable_volleyball_pattern', models.BooleanField(default=True)),
                ('nepal_pattern_svg', models.TextField(blank=True)),
                ('volleyball_pattern_svg', models.TextField(blank=True)),
                ('transition_duration', models.PositiveIntegerField(default=300, help_text='in ms')),
            ],
            options={
                'verbose_name': 'Global Styles & Brand',
                'verbose_name_plural': 'Global Styles & Brand',
            },
        ),
    ]
