# Generated by Django 6.0.2 on 2026-03-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name / Company Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('sponsorship_type', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_voucher', models.ImageField(upload_to='images/sponsorship/applications/vouchers/')),
                ('message', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsorship Application',
                'verbose_name_plural': 'Sponsorship Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'Sponsorship Page',
                'verbose_name_plural': 'Sponsorship Pages',
            },
        ),
        migrations.CreateModel(
            name='SponsorshipHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sponsorship/hero/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Hero Image URL (CDN)')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Hero Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Hero Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Hero Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Hero Text (NE)')),
                ('text_en', models.TextField(verbose_name='Hero Text (EN)')),
                ('text_de', models.TextField(verbose_name='Hero Text (DE)')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='sponsorship_options.sponsorshippage')),
            ],
            options={
                'verbose_name': 'Sponsorship Hero',
            },
        ),
        migrations.CreateModel(
            name='SponsorshipFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Form Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Form Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Form Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Form Text (NE)')),
                ('text_en', models.TextField(verbose_name='Form Text (EN)')),
                ('text_de', models.TextField(verbose_name='Form Text (DE)')),
                ('success_title_ne', models.CharField(max_length=200, verbose_name='Success Title (NE)')),
                ('success_title_en', models.CharField(max_length=200, verbose_name='Success Title (EN)')),
                ('success_title_de', models.CharField(max_length=200, verbose_name='Success Title (DE)')),
                ('success_text_ne', models.TextField(verbose_name='Success Text (NE)')),
                ('success_text_en', models.TextField(verbose_name='Success Text (EN)')),
                ('success_text_de', models.TextField(verbose_name='Success Text (DE)')),
                ('label_name_ne', models.CharField(default='पूरा नाम / संस्थाको नाम', max_length=100)),
                ('label_name_en', models.CharField(default='Full Name / Company Name', max_length=100)),
                ('label_name_de', models.CharField(default='Vollständiger Name / Firmenname', max_length=100)),
                ('label_email_ne', models.CharField(default='ईमेल', max_length=100)),
                ('label_email_en', models.CharField(default='Email Address', max_length=100)),
                ('label_email_de', models.CharField(default='E-Mail-Adresse', max_length=100)),
                ('label_phone_ne', models.CharField(default='फोन नम्बर', max_length=100)),
                ('label_phone_en', models.CharField(default='Phone Number', max_length=100)),
                ('label_phone_de', models.CharField(default='Telefonnummer', max_length=100)),
                ('label_type_ne', models.CharField(default='प्रयोजन प्रकार', max_length=100)),
                ('label_type_en', models.CharField(default='Sponsorship Type', max_length=100)),
                ('label_type_de', models.CharField(default='Sponsoring-Typ', max_length=100)),
                ('label_amount_ne', models.CharField(default='प्रयोजन रकम (€)', max_length=100)),
                ('label_amount_en', models.CharField(default='Sponsorship Amount (€)', max_length=100)),
                ('label_amount_de', models.CharField(default='Sponsoring-Betrag (€)', max_length=100)),
                ('label_voucher_ne', models.CharField(default='बैंक भौचर फोटो', max_length=100)),
                ('label_voucher_en', models.CharField(default='Bank Voucher Photo', max_length=100)),
                ('label_voucher_de', models.CharField(default='Bankbeleg Foto', max_length=100)),
                ('label_message_ne', models.CharField(default='सन्देश', max_length=100)),
                ('label_message_en', models.CharField(default='Message', max_length=100)),
                ('label_message_de', models.CharField(default='Nachricht', max_length=100)),
                ('label_submit_ne', models.CharField(default='आवेदन पठाउनुहोस्', max_length=100)),
                ('label_submit_en', models.CharField(default='Submit Application', max_length=100)),
                ('label_submit_de', models.CharField(default='Antrag absenden', max_length=100)),
                ('options_type_ne', models.CharField(default='प्लेटिनम, गोल्ड, सिल्भर, अन्य', max_length=500)),
                ('options_type_en', models.CharField(default='Platinum, Gold, Silver, Other', max_length=500)),
                ('options_type_de', models.CharField(default='Platin, Gold, Silber, Sonstiges', max_length=500)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_settings', to='sponsorship_options.sponsorshippage')),
            ],
            options={
                'verbose_name': 'Form Settings & Labels',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(max_length=200, verbose_name='Sponsor Name (NE)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Sponsor Name (EN)')),
                ('name_de', models.CharField(max_length=200, verbose_name='Sponsor Name (DE)')),
                ('logo', models.ImageField(upload_to='images/sponsorship/logos/')),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='sponsorship_options.sponsorshippage')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipFormProxy',
            fields=[
            ],
            options={
                'verbose_name': '04: Form & Labels',
                'verbose_name_plural': '04: Form & Labels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sponsorship_options.sponsorshippage',),
        ),
        migrations.CreateModel(
            name='SponsorshipHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': '02: Hero Section',
                'verbose_name_plural': '02: Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sponsorship_options.sponsorshippage',),
        ),
        migrations.CreateModel(
            name='SponsorshipPageProxy',
            fields=[
            ],
            options={
                'verbose_name': '01: Main Settings',
                'verbose_name_plural': '01: Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sponsorship_options.sponsorshippage',),
        ),
        migrations.CreateModel(
            name='SponsorsProxy',
            fields=[
            ],
            options={
                'verbose_name': '03: Current Sponsors',
                'verbose_name_plural': '03: Current Sponsors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sponsorship_options.sponsorshippage',),
        ),
    ]
