# Generated by Django 6.0.2 on 2026-02-17 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'Committee Page',
                'verbose_name_plural': 'Committee Pages',
                'db_table': 'pages_committeepage',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_ne', models.CharField(max_length=200, verbose_name='Role (NE)')),
                ('role_en', models.CharField(max_length=200, verbose_name='Role (EN)')),
                ('role_de', models.CharField(max_length=200, verbose_name='Role (DE)')),
                ('description_ne', models.TextField(blank=True, verbose_name='Description (NE)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('description_de', models.TextField(blank=True, verbose_name='Description (DE)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/committee/members/')),
                ('is_executive', models.BooleanField(default=False, verbose_name='Is Executive Board Member?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='committee_options.committeepage')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Committee Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Hero Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Hero Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Hero Title (DE)')),
                ('subtitle_ne', models.CharField(max_length=300, verbose_name='Hero Subtitle (NE)')),
                ('subtitle_en', models.CharField(max_length=300, verbose_name='Hero Subtitle (EN)')),
                ('subtitle_de', models.CharField(max_length=300, verbose_name='Hero Subtitle (DE)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='images/committee/hero/', verbose_name='Background Image')),
                ('background_color', models.CharField(default='#030712', max_length=20, verbose_name='Background Color (if no image)')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='committee_options.committeepage')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeExecutiveProxy',
            fields=[
            ],
            options={
                'verbose_name': '03. Executive Board',
                'verbose_name_plural': '03. Executive Board',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('committee_options.committeepage',),
        ),
        migrations.CreateModel(
            name='CommitteeGeneralProxy',
            fields=[
            ],
            options={
                'verbose_name': '04. General Members',
                'verbose_name_plural': '04. General Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('committee_options.committeepage',),
        ),
        migrations.CreateModel(
            name='CommitteeHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': '02. Hero Section',
                'verbose_name_plural': '02. Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('committee_options.committeepage',),
        ),
        migrations.CreateModel(
            name='CommitteePageProxy',
            fields=[
            ],
            options={
                'verbose_name': '01. Main Settings',
                'verbose_name_plural': '01. Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('committee_options.committeepage',),
        ),
        migrations.CreateModel(
            name='CommitteeTitleProxy',
            fields=[
            ],
            options={
                'verbose_name': '05. Section Titles',
                'verbose_name_plural': '05. Section Titles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('committee_options.committeepage',),
        ),
        migrations.CreateModel(
            name='CommitteeSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_section_title_ne', models.CharField(default='कार्यसमिति सदस्यहरू', max_length=200, verbose_name='Member Section Title (NE)')),
                ('member_section_title_en', models.CharField(default='Committee Members', max_length=200, verbose_name='Member Section Title (EN)')),
                ('member_section_title_de', models.CharField(default='Vorstandsmitglieder', max_length=200, verbose_name='Member Section Title (DE)')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_settings', to='committee_options.committeepage')),
            ],
        ),
    ]
