# Generated by Django 6.0.2 on 2026-02-17 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_options', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'General Member', 'verbose_name_plural': 'General Members'},
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='description_ne',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='is_executive',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='role_de',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='role_en',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='role_ne',
        ),
        migrations.CreateModel(
            name='CommitteeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_name', models.CharField(max_length=200, verbose_name='President Name')),
                ('pres_role_ne', models.CharField(max_length=200, verbose_name='President Role (NE)')),
                ('pres_role_en', models.CharField(max_length=200, verbose_name='President Role (EN)')),
                ('pres_role_de', models.CharField(max_length=200, verbose_name='President Role (DE)')),
                ('pres_desc_ne', models.TextField(blank=True, verbose_name='President Description (NE)')),
                ('pres_desc_en', models.TextField(blank=True, verbose_name='President Description (EN)')),
                ('pres_desc_de', models.TextField(blank=True, verbose_name='President Description (DE)')),
                ('pres_image', models.ImageField(blank=True, null=True, upload_to='images/committee/board/', verbose_name='President Image')),
                ('pres_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='President Email')),
                ('sec_name', models.CharField(max_length=200, verbose_name='Secretary Name')),
                ('sec_role_ne', models.CharField(max_length=200, verbose_name='Secretary Role (NE)')),
                ('sec_role_en', models.CharField(max_length=200, verbose_name='Secretary Role (EN)')),
                ('sec_role_de', models.CharField(max_length=200, verbose_name='Secretary Role (DE)')),
                ('sec_desc_ne', models.TextField(blank=True, verbose_name='Secretary Description (NE)')),
                ('sec_desc_en', models.TextField(blank=True, verbose_name='Secretary Description (EN)')),
                ('sec_desc_de', models.TextField(blank=True, verbose_name='Secretary Description (DE)')),
                ('sec_image', models.ImageField(blank=True, null=True, upload_to='images/committee/board/', verbose_name='Secretary Image')),
                ('sec_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secretary Email')),
                ('tres_name', models.CharField(max_length=200, verbose_name='Treasurer Name')),
                ('tres_role_ne', models.CharField(max_length=200, verbose_name='Treasurer Role (NE)')),
                ('tres_role_en', models.CharField(max_length=200, verbose_name='Treasurer Role (EN)')),
                ('tres_role_de', models.CharField(max_length=200, verbose_name='Treasurer Role (DE)')),
                ('tres_desc_ne', models.TextField(blank=True, verbose_name='Treasurer Description (NE)')),
                ('tres_desc_en', models.TextField(blank=True, verbose_name='Treasurer Description (EN)')),
                ('tres_desc_de', models.TextField(blank=True, verbose_name='Treasurer Description (DE)')),
                ('tres_image', models.ImageField(blank=True, null=True, upload_to='images/committee/board/', verbose_name='Treasurer Image')),
                ('tres_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Treasurer Email')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='committee_options.committeepage')),
            ],
        ),
    ]
