# Generated by hand for dynamic groups implementation

import django.db.models.deletion
from django.db import migrations, models

def migrate_members_to_groups(apps, schema_editor):
    CommitteePage = apps.get_model('committee_options', 'CommitteePage')
    CommitteeGroup = apps.get_model('committee_options', 'CommitteeGroup')
    CommitteeMember = apps.get_model('committee_options', 'CommitteeMember')

    for page in CommitteePage.objects.all():
        # Create a default "General Members" group for each page
        group = CommitteeGroup.objects.create(
            page=page,
            title_ne="साधारण सदस्यहरू",
            title_en="General Members",
            title_de="Allgemeine Mitglieder",
            order=0
        )
        # Move all members belonging to this page into the new group
        members = CommitteeMember.objects.filter(page=page)
        for member in members:
            member.group = group
            member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('committee_options', '0002_alter_committeemember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Group Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Group Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Group Title (DE)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='committee_options.committeepage')),
            ],
            options={
                'verbose_name': 'Committee Group',
                'verbose_name_plural': 'Committee Groups',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='committeemember',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='committee_options.committeegroup'),
        ),
        migrations.RunPython(migrate_members_to_groups),
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Committee Member', 'verbose_name_plural': 'Committee Members'},
        ),
    ]
