# Generated by Django 6.0.2 on 2026-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_options', '0003_dynamic_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommitteeGeneralProxy',
        ),
        migrations.CreateModel(
            name='CommitteeGroupProxy',
            fields=[
            ],
            options={
                'verbose_name': '04. Committee Groups',
                'verbose_name_plural': '04. Committee Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('committee_options.committeepage',),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='name_de',
            field=models.CharField(default='', max_length=200, verbose_name='Name (DE)'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='name_en',
            field=models.CharField(default='', max_length=200, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='name_ne',
            field=models.CharField(default='', max_length=200, verbose_name='Name (NE)'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
