# Generated by Django 6.0.2 on 2026-03-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_options', '0004_delete_committeegeneralproxy_committeegroupproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('role_ne', models.CharField(max_length=200, verbose_name='Role (NE)')),
                ('role_en', models.CharField(max_length=200, verbose_name='Role (EN)')),
                ('role_de', models.CharField(max_length=200, verbose_name='Role (DE)')),
                ('desc_ne', models.TextField(blank=True, verbose_name='Description (NE)')),
                ('desc_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('desc_de', models.TextField(blank=True, verbose_name='Description (DE)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/committee/executives/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='committee_options.committeepage')),
            ],
            options={
                'verbose_name': 'Executive Member',
                'verbose_name_plural': 'Executive Members',
                'ordering': ['order'],
            },
        ),
    ]
