# Generated by Django 6.0.2 on 2026-03-24 15:54

from django.db import migrations


def transfer_executives(apps, schema_editor):
    CommitteeBoard = apps.get_model('committee_options', 'CommitteeBoard')
    ExecutiveMember = apps.get_model('committee_options', 'ExecutiveMember')
    
    for board in CommitteeBoard.objects.all():
        if board.pres_name:
            ExecutiveMember.objects.create(
                page=board.page,
                name=board.pres_name,
                role_ne=board.pres_role_ne,
                role_en=board.pres_role_en,
                role_de=board.pres_role_de,
                desc_ne=board.pres_desc_ne,
                desc_en=board.pres_desc_en,
                desc_de=board.pres_desc_de,
                image=board.pres_image,
                email=board.pres_email,
                order=1
            )
        if board.sec_name:
            ExecutiveMember.objects.create(
                page=board.page,
                name=board.sec_name,
                role_ne=board.sec_role_ne,
                role_en=board.sec_role_en,
                role_de=board.sec_role_de,
                desc_ne=board.sec_desc_ne,
                desc_en=board.sec_desc_en,
                desc_de=board.sec_desc_de,
                image=board.sec_image,
                email=board.sec_email,
                order=2
            )
        if board.tres_name:
            ExecutiveMember.objects.create(
                page=board.page,
                name=board.tres_name,
                role_ne=board.tres_role_ne,
                role_en=board.tres_role_en,
                role_de=board.tres_role_de,
                desc_ne=board.tres_desc_ne,
                desc_en=board.tres_desc_en,
                desc_de=board.tres_desc_de,
                image=board.tres_image,
                email=board.tres_email,
                order=3
            )

def reverse_transfer(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('committee_options', '0005_add_executive_member'),
    ]

    operations = [
        migrations.RunPython(transfer_executives, reverse_transfer),
    ]
