# Generated by Django 6.0.2 on 2026-03-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee_options', '0006_transfer_executive_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommitteeBoard',
        ),
    ]
