# Generated by Django 6.0.2 on 2026-03-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee_options', '0007_drop_committee_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='role_de',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Role (DE)'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='role_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Role (EN)'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='role_ne',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Role (NE)'),
        ),
    ]
