# Generated by Django 6.0.2 on 2026-02-17 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'Events Page',
                'verbose_name_plural': 'Events Pages',
            },
        ),
        migrations.CreateModel(
            name='EventsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/events/hero/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Hero Image URL (CDN)')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Hero Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Hero Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Hero Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Hero Text (NE)')),
                ('text_en', models.TextField(verbose_name='Hero Text (EN)')),
                ('text_de', models.TextField(verbose_name='Hero Text (DE)')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='events_options.eventspage')),
            ],
            options={
                'verbose_name': 'Events Hero',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_de', models.CharField(max_length=200)),
                ('description_ne', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('date_text_ne', models.CharField(help_text='e.g. मार्च १५, २०२६', max_length=100)),
                ('date_text_en', models.CharField(help_text='e.g. March 15, 2026', max_length=100)),
                ('date_text_de', models.CharField(help_text='e.g. 15. März 2026', max_length=100)),
                ('time', models.CharField(blank=True, help_text='e.g. 10:00 AM', max_length=100)),
                ('location_ne', models.CharField(blank=True, max_length=200)),
                ('location_en', models.CharField(blank=True, max_length=200)),
                ('location_de', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/events/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Event Image URL')),
                ('is_past', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events_options.eventspage')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventsHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': '02: Hero Section',
                'verbose_name_plural': '02: Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events_options.eventspage',),
        ),
        migrations.CreateModel(
            name='EventsLabelsProxy',
            fields=[
            ],
            options={
                'verbose_name': '04: Labels & Settings',
                'verbose_name_plural': '04: Labels & Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events_options.eventspage',),
        ),
        migrations.CreateModel(
            name='EventsManagementProxy',
            fields=[
            ],
            options={
                'verbose_name': '03: Events Management',
                'verbose_name_plural': '03: Events Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events_options.eventspage',),
        ),
        migrations.CreateModel(
            name='EventsPageProxy',
            fields=[
            ],
            options={
                'verbose_name': '01: Main Settings',
                'verbose_name_plural': '01: Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events_options.eventspage',),
        ),
        migrations.CreateModel(
            name='EventsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_title_ne', models.CharField(default='आगामी कार्यक्रमहरू', max_length=200)),
                ('upcoming_title_en', models.CharField(default='Upcoming Events', max_length=200)),
                ('upcoming_title_de', models.CharField(default='Kommende Veranstaltungen', max_length=200)),
                ('past_title_ne', models.CharField(default='विगतका कार्यक्रमहरू', max_length=200)),
                ('past_title_en', models.CharField(default='Past Events', max_length=200)),
                ('past_title_de', models.CharField(default='Vergangene Veranstaltungen', max_length=200)),
                ('register_btn_ne', models.CharField(default='दर्ता गर्नुहोस्', max_length=100)),
                ('register_btn_en', models.CharField(default='Register', max_length=100)),
                ('register_btn_de', models.CharField(default='Registrieren', max_length=100)),
                ('label_upcoming_ne', models.CharField(default='आगामी', max_length=100)),
                ('label_upcoming_en', models.CharField(default='Upcoming', max_length=100)),
                ('label_upcoming_de', models.CharField(default='Kommende', max_length=100)),
                ('label_past_ne', models.CharField(default='विगत', max_length=100)),
                ('label_past_en', models.CharField(default='Past', max_length=100)),
                ('label_past_de', models.CharField(default='Vergangene', max_length=100)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='events_options.eventspage')),
            ],
            options={
                'verbose_name': 'Events Labels & Settings',
            },
        ),
    ]
