# Generated by Django 6.0.2 on 2026-02-17 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategoriesProxy',
            fields=[
            ],
            options={
                'verbose_name': '03: Categories',
                'verbose_name_plural': '03: Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news_options.newscategory',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'News Page',
                'verbose_name_plural': 'News Pages',
            },
        ),
        migrations.CreateModel(
            name='NewsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news/hero/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Hero Image URL (CDN)')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Hero Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Hero Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Hero Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Hero Text (NE)')),
                ('text_en', models.TextField(verbose_name='Hero Text (EN)')),
                ('text_de', models.TextField(verbose_name='Hero Text (DE)')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='news_options.newspage')),
            ],
            options={
                'verbose_name': 'News Hero',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_de', models.CharField(max_length=200)),
                ('excerpt_ne', models.TextField(blank=True)),
                ('excerpt_en', models.TextField(blank=True)),
                ('excerpt_de', models.TextField(blank=True)),
                ('content_ne', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('content_de', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news/articles/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Article Image URL')),
                ('date_text_ne', models.CharField(help_text='e.g. फेब्रुअरी २५, २०२६', max_length=100)),
                ('date_text_en', models.CharField(help_text='e.g. February 25, 2026', max_length=100)),
                ('date_text_de', models.CharField(help_text='e.g. 25. Februar 2026', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news_options.newscategory')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news_options.newspage')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticlesProxy',
            fields=[
            ],
            options={
                'verbose_name': '04: Articles',
                'verbose_name_plural': '04: Articles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news_options.newspage',),
        ),
        migrations.CreateModel(
            name='NewsHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': '02: Hero Section',
                'verbose_name_plural': '02: Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news_options.newspage',),
        ),
        migrations.CreateModel(
            name='NewsLabelsProxy',
            fields=[
            ],
            options={
                'verbose_name': '05: Labels & Settings',
                'verbose_name_plural': '05: Labels & Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news_options.newspage',),
        ),
        migrations.CreateModel(
            name='NewsPageProxy',
            fields=[
            ],
            options={
                'verbose_name': '01: Main Settings',
                'verbose_name_plural': '01: Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news_options.newspage',),
        ),
        migrations.CreateModel(
            name='NewsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_label_ne', models.CharField(default='मुख्य समाचार', max_length=100)),
                ('featured_label_en', models.CharField(default='Featured News', max_length=100)),
                ('featured_label_de', models.CharField(default='Top-Nachricht', max_length=100)),
                ('read_more_label_ne', models.CharField(default='पूरा पढ्नुहोस्', max_length=100)),
                ('read_more_label_en', models.CharField(default='Read More', max_length=100)),
                ('read_more_label_de', models.CharField(default='Weiterlesen', max_length=100)),
                ('other_news_title_ne', models.CharField(default='अन्य समाचार', max_length=200)),
                ('other_news_title_en', models.CharField(default='Other News', max_length=200)),
                ('other_news_title_de', models.CharField(default='Weitere Neuigkeiten', max_length=200)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='news_options.newspage')),
            ],
            options={
                'verbose_name': 'News Labels & Settings',
            },
        ),
    ]
