# Generated by Django 6.0.2 on 2026-02-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Section Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Section Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Section Title (DE)')),
                ('vision_title_ne', models.CharField(max_length=100, verbose_name='Vision Title (NE)')),
                ('vision_title_en', models.CharField(max_length=100, verbose_name='Vision Title (EN)')),
                ('vision_title_de', models.CharField(max_length=100, verbose_name='Vision Title (DE)')),
                ('vision_text_ne', models.TextField(verbose_name='Vision Text (NE)')),
                ('vision_text_en', models.TextField(verbose_name='Vision Text (EN)')),
                ('vision_text_de', models.TextField(verbose_name='Vision Text (DE)')),
                ('vision_icon', models.CharField(default='Eye', max_length=50, verbose_name='Vision Icon (Lucide name)')),
                ('mission_title_ne', models.CharField(max_length=100, verbose_name='Mission Title (NE)')),
                ('mission_title_en', models.CharField(max_length=100, verbose_name='Mission Title (EN)')),
                ('mission_title_de', models.CharField(max_length=100, verbose_name='Mission Title (DE)')),
                ('mission_text_ne', models.TextField(verbose_name='Mission Text (NE)')),
                ('mission_text_en', models.TextField(verbose_name='Mission Text (EN)')),
                ('mission_text_de', models.TextField(verbose_name='Mission Text (DE)')),
                ('mission_icon', models.CharField(default='Target', max_length=50, verbose_name='Mission Icon (Lucide name)')),
            ],
            options={
                'verbose_name': 'About Core (Vision/Mission)',
                'db_table': 'pages_aboutcore',
            },
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_text_ne', models.CharField(max_length=100, verbose_name='Since Text (NE)')),
                ('since_text_en', models.CharField(max_length=100, verbose_name='Since Text (EN)')),
                ('since_text_de', models.CharField(max_length=100, verbose_name='Since Text (DE)')),
                ('show_pulsing_dot', models.BooleanField(default=True, verbose_name='Show Pulsing Dot Icon')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Hero Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Hero Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Hero Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Hero Text (NE)')),
                ('text_en', models.TextField(verbose_name='Hero Text (EN)')),
                ('text_de', models.TextField(verbose_name='Hero Text (DE)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='images/about/hero/', verbose_name='Background Image')),
                ('background_color', models.CharField(default='#030712', max_length=20, verbose_name='Background Color (Hex)')),
            ],
            options={
                'verbose_name': 'About Hero',
                'db_table': 'pages_abouthero',
            },
        ),
        migrations.CreateModel(
            name='AboutIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part1_ne', models.CharField(max_length=100, verbose_name='Title Part 1 (NE)')),
                ('title_part1_en', models.CharField(max_length=100, verbose_name='Title Part 1 (EN)')),
                ('title_part1_de', models.CharField(max_length=100, verbose_name='Title Part 1 (DE)')),
                ('title_part2_ne', models.CharField(max_length=100, verbose_name='Title Part 2 (NE)')),
                ('title_part2_en', models.CharField(max_length=100, verbose_name='Title Part 2 (EN)')),
                ('title_part2_de', models.CharField(max_length=100, verbose_name='Title Part 2 (DE)')),
                ('text1_ne', models.TextField(verbose_name='Main Text Paragraph 1 (NE)')),
                ('text1_en', models.TextField(verbose_name='Main Text Paragraph 1 (EN)')),
                ('text1_de', models.TextField(verbose_name='Main Text Paragraph 1 (DE)')),
                ('text2_ne', models.TextField(verbose_name='Main Text Paragraph 2 (NE)')),
                ('text2_en', models.TextField(verbose_name='Main Text Paragraph 2 (EN)')),
                ('text2_de', models.TextField(verbose_name='Main Text Paragraph 2 (DE)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/about/intro/', verbose_name='Main Image')),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='images/about/intro/', verbose_name='Secondary Overlay Image')),
                ('established_label_ne', models.CharField(max_length=50, verbose_name='Established Label (NE)')),
                ('established_label_en', models.CharField(max_length=50, verbose_name='Established Label (EN)')),
                ('established_label_de', models.CharField(max_length=50, verbose_name='Established Label (DE)')),
                ('established_year', models.CharField(default='2020', max_length=10, verbose_name='Established Year')),
            ],
            options={
                'verbose_name': 'About Intro',
                'db_table': 'pages_aboutintro',
            },
        ),
        migrations.CreateModel(
            name='AboutCoreProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 4: Vision & Mission',
                'verbose_name_plural': 'Step 4: Vision & Mission',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about_options.aboutcore',),
        ),
        migrations.CreateModel(
            name='AboutHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 2: Hero Section',
                'verbose_name_plural': 'Step 2: Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about_options.abouthero',),
        ),
        migrations.CreateModel(
            name='AboutIntroProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 3: Intro Section',
                'verbose_name_plural': 'Step 3: Intro Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about_options.aboutintro',),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
                'db_table': 'pages_aboutpage',
            },
        ),
        migrations.AddField(
            model_name='aboutintro',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intro', to='about_options.aboutpage'),
        ),
        migrations.AddField(
            model_name='abouthero',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='about_options.aboutpage'),
        ),
        migrations.AddField(
            model_name='aboutcore',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core', to='about_options.aboutpage'),
        ),
        migrations.CreateModel(
            name='AboutPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 1: Main Settings',
                'verbose_name_plural': 'Step 1: Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about_options.aboutpage',),
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ne', models.CharField(max_length=100, verbose_name='Label (NE)')),
                ('label_en', models.CharField(max_length=100, verbose_name='Label (EN)')),
                ('label_de', models.CharField(max_length=100, verbose_name='Label (DE)')),
                ('value', models.CharField(max_length=20, verbose_name='Value (e.g. 50+)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('intro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about_options.aboutintro')),
            ],
            options={
                'verbose_name': 'About Stat',
                'db_table': 'pages_aboutstat',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStrategic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_title_ne', models.CharField(max_length=200, verbose_name='Label (NE)')),
                ('strategic_title_en', models.CharField(max_length=200, verbose_name='Label (EN)')),
                ('strategic_title_de', models.CharField(max_length=200, verbose_name='Label (DE)')),
                ('objectives_title_ne', models.CharField(max_length=200, verbose_name='Objectives Title (NE)')),
                ('objectives_title_en', models.CharField(max_length=200, verbose_name='Objectives Title (EN)')),
                ('objectives_title_de', models.CharField(max_length=200, verbose_name='Objectives Title (DE)')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='images/about/strategic/', verbose_name='Side Graphic Image')),
                ('promo_title_ne', models.CharField(max_length=200, verbose_name='Promo Title (NE)')),
                ('promo_title_en', models.CharField(max_length=200, verbose_name='Promo Title (EN)')),
                ('promo_title_de', models.CharField(max_length=200, verbose_name='Promo Title (DE)')),
                ('promo_text_ne', models.TextField(verbose_name='Promo Text (NE)')),
                ('promo_text_en', models.TextField(verbose_name='Promo Text (EN)')),
                ('promo_text_de', models.TextField(verbose_name='Promo Text (DE)')),
                ('promo_icon', models.CharField(default='Globe', max_length=50, verbose_name='Promo Icon (Lucide name)')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategic', to='about_options.aboutpage')),
            ],
            options={
                'verbose_name': 'About Strategic',
                'db_table': 'pages_aboutstrategic',
            },
        ),
        migrations.CreateModel(
            name='AboutObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ne', models.TextField(verbose_name='Objective Text (NE)')),
                ('text_en', models.TextField(verbose_name='Objective Text (EN)')),
                ('text_de', models.TextField(verbose_name='Objective Text (DE)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('strategic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='about_options.aboutstrategic')),
            ],
            options={
                'verbose_name': 'About Objective',
                'db_table': 'pages_aboutobjective',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStrategicProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 5: Strategic Goals',
                'verbose_name_plural': 'Step 5: Strategic Goals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about_options.aboutstrategic',),
        ),
    ]
