# Generated by Django 6.0.2 on 2026-02-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/hero/', verbose_name='Video File (Upload)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL (YouTube/CDN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/hero/', verbose_name='Fallback/Background Image (Upload)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Background Image URL (External/CDN)')),
                ('title_ne', models.TextField(verbose_name='Title (NE)')),
                ('title_en', models.TextField(verbose_name='Title (EN)')),
                ('title_de', models.TextField(verbose_name='Title (DE)')),
                ('subtitle_ne', models.TextField(verbose_name='Subtitle (NE)')),
                ('subtitle_en', models.TextField(verbose_name='Subtitle (EN)')),
                ('subtitle_de', models.TextField(verbose_name='Subtitle (DE)')),
                ('cta_join_label_ne', models.CharField(max_length=100, verbose_name='Join CTA (NE)')),
                ('cta_join_label_en', models.CharField(max_length=100, verbose_name='Join CTA (EN)')),
                ('cta_join_label_de', models.CharField(max_length=100, verbose_name='Join CTA (DE)')),
                ('cta_learn_label_ne', models.CharField(max_length=100, verbose_name='Learn CTA (NE)')),
                ('cta_learn_label_en', models.CharField(max_length=100, verbose_name='Learn CTA (EN)')),
                ('cta_learn_label_de', models.CharField(max_length=100, verbose_name='Learn CTA (DE)')),
            ],
            options={
                'verbose_name': 'Home Hero',
                'db_table': 'pages_homehero',
            },
        ),
        migrations.CreateModel(
            name='HomeIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/intro/', verbose_name='Image File (Upload)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL (External/CDN)')),
                ('mini_header_ne', models.CharField(max_length=200, verbose_name='Mini Header (NE)')),
                ('mini_header_en', models.CharField(max_length=200, verbose_name='Mini Header (EN)')),
                ('mini_header_de', models.CharField(max_length=200, verbose_name='Mini Header (DE)')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Text (NE)')),
                ('text_en', models.TextField(verbose_name='Text (EN)')),
                ('text_de', models.TextField(verbose_name='Text (DE)')),
                ('subtext_ne', models.TextField(verbose_name='Subtext (NE)')),
                ('subtext_en', models.TextField(verbose_name='Subtext (EN)')),
                ('subtext_de', models.TextField(verbose_name='Subtext (DE)')),
            ],
            options={
                'verbose_name': 'Home Intro',
                'db_table': 'pages_homeintro',
            },
        ),
        migrations.CreateModel(
            name='HomeMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_label_ne', models.CharField(max_length=100, verbose_name='Label (NE)')),
                ('mission_label_en', models.CharField(max_length=100, verbose_name='Label (EN)')),
                ('mission_label_de', models.CharField(max_length=100, verbose_name='Label (DE)')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Title (DE)')),
                ('description_ne', models.TextField(verbose_name='Description (NE)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('description_de', models.TextField(verbose_name='Description (DE)')),
            ],
            options={
                'verbose_name': 'Home Mission',
                'db_table': 'pages_homemission',
            },
        ),
        migrations.CreateModel(
            name='HomeMotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ne', models.TextField(verbose_name='Motto (NE)')),
                ('text_en', models.TextField(verbose_name='Motto (EN)')),
                ('text_de', models.TextField(verbose_name='Motto (DE)')),
                ('button_label_ne', models.CharField(max_length=100, verbose_name='Button (NE)')),
                ('button_label_en', models.CharField(max_length=100, verbose_name='Button (EN)')),
                ('button_label_de', models.CharField(max_length=100, verbose_name='Button (DE)')),
            ],
            options={
                'verbose_name': 'Home Motto',
                'db_table': 'pages_homemotto',
            },
        ),
        migrations.CreateModel(
            name='HomeHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 2: Hero Section',
                'verbose_name_plural': 'Step 2: Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homepage_options.homehero',),
        ),
        migrations.CreateModel(
            name='HomeIntroProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 3: Intro Section',
                'verbose_name_plural': 'Step 3: Intro Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homepage_options.homeintro',),
        ),
        migrations.CreateModel(
            name='HomeMissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 4: Mission Section',
                'verbose_name_plural': 'Step 4: Mission Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homepage_options.homemission',),
        ),
        migrations.CreateModel(
            name='HomeMottoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 6: Motto Section',
                'verbose_name_plural': 'Step 6: Motto Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homepage_options.homemotto',),
        ),
        migrations.CreateModel(
            name='HomeObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/objectives/', verbose_name='Image (Upload)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL (CDN)')),
                ('badge_number', models.CharField(default='01', max_length=10)),
                ('text_ne', models.TextField(verbose_name='Text (NE)')),
                ('text_en', models.TextField(verbose_name='Text (EN)')),
                ('text_de', models.TextField(verbose_name='Text (DE)')),
                ('goal_prefix_ne', models.CharField(default='Goal', max_length=50, verbose_name='Prefix (NE)')),
                ('goal_prefix_en', models.CharField(default='Goal', max_length=50, verbose_name='Prefix (EN)')),
                ('goal_prefix_de', models.CharField(default='Ziel', max_length=50, verbose_name='Prefix (DE)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='homepage_options.homemission')),
            ],
            options={
                'verbose_name': 'Home Objective',
                'db_table': 'pages_homeobjective',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeObjectiveProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 5: Objectives',
                'verbose_name_plural': 'Step 5: Objectives',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homepage_options.homeobjective',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
                'db_table': 'pages_homepage',
            },
        ),
        migrations.AddField(
            model_name='homemotto',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motto', to='homepage_options.homepage'),
        ),
        migrations.AddField(
            model_name='homemission',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='homepage_options.homepage'),
        ),
        migrations.AddField(
            model_name='homeintro',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intro', to='homepage_options.homepage'),
        ),
        migrations.AddField(
            model_name='homehero',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='homepage_options.homepage'),
        ),
        migrations.CreateModel(
            name='HomePageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 1: Main Settings',
                'verbose_name_plural': 'Step 1: Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homepage_options.homepage',),
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ne', models.CharField(max_length=100, verbose_name='Label (NE)')),
                ('label_en', models.CharField(max_length=100, verbose_name='Label (EN)')),
                ('label_de', models.CharField(max_length=100, verbose_name='Label (DE)')),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(default='+', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='homepage_options.homepage')),
            ],
            options={
                'verbose_name': 'Home Stat',
                'db_table': 'pages_homestat',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeStatProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Step 7: Stats',
                'verbose_name_plural': 'Step 7: Stats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('homepage_options.homestat',),
        ),
    ]
