# Generated by Django for Notice Options App

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Notice Category',
                'verbose_name_plural': 'Notice Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NoticePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_options_noticepage_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'Notice Page',
                'verbose_name_plural': 'Notice Pages',
            },
        ),
        migrations.CreateModel(
            name='NoticeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Hero Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Hero Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Hero Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Hero Text (NE)')),
                ('text_en', models.TextField(verbose_name='Hero Text (EN)')),
                ('text_de', models.TextField(verbose_name='Hero Text (DE)')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='notice_options.noticepage')),
            ],
            options={
                'verbose_name': 'Notice Hero',
            },
        ),
        migrations.CreateModel(
            name='NoticeCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(default='सूचना प्राप्त गर्नुहोस्', max_length=200)),
                ('title_en', models.CharField(default='Get Notifications', max_length=200)),
                ('title_de', models.CharField(default='Benachrichtigungen erhalten', max_length=200)),
                ('text_ne', models.TextField(default='नयाँ सूचना आएपछि इमेलमा जानकारी पाउनुहोस्।')),
                ('text_en', models.TextField(default='Get notified via email when new notices are published.')),
                ('text_de', models.TextField(default='Lassen Sie sich per E-Mail benachrichtigen, wenn neue Mitteilungen veröffentlicht werden.')),
                ('button_text_ne', models.CharField(default='सम्पर्क गर्नुहोस्', max_length=100)),
                ('button_text_en', models.CharField(default='Contact Us', max_length=100)),
                ('button_text_de', models.CharField(default='Kontaktieren Sie uns', max_length=100)),
                ('button_icon', models.CharField(default='ChevronRight', help_text='Lucide icon name', max_length=50)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='notice_options.noticepage')),
            ],
            options={
                'verbose_name': 'Notice CTA Section',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_de', models.CharField(max_length=200)),
                ('content_ne', models.TextField()),
                ('content_en', models.TextField()),
                ('content_de', models.TextField()),
                ('date_text_ne', models.CharField(help_text='e.g. फेब्रुअरी २८, २०२६', max_length=100)),
                ('date_text_en', models.CharField(help_text='e.g. February 25, 2026', max_length=100)),
                ('date_text_de', models.CharField(help_text='e.g. 25. Februar 2026', max_length=100)),
                ('icon', models.CharField(default='Bell', help_text='Lucide icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='notice_options.noticecategory')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='notice_options.noticepage')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['order'],
            },
        ),
        # Proxy models
        migrations.CreateModel(
            name='NoticePageProxy',
            fields=[
            ],
            options={
                'verbose_name': '01: Main Settings',
                'verbose_name_plural': '01: Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notice_options.noticepage',),
        ),
        migrations.CreateModel(
            name='NoticeHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': '02: Hero Section',
                'verbose_name_plural': '02: Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notice_options.noticepage',),
        ),
        migrations.CreateModel(
            name='NoticeCTAProxy',
            fields=[
            ],
            options={
                'verbose_name': '03: CTA Section',
                'verbose_name_plural': '03: CTA Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notice_options.noticepage',),
        ),
        migrations.CreateModel(
            name='NoticeManagementProxy',
            fields=[
            ],
            options={
                'verbose_name': '04: Notices Management',
                'verbose_name_plural': '04: Notices Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notice_options.noticepage',),
        ),
    ]