# Generated by Django 4.2.16 on 2026-02-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('notice_options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date_text_ne',
            field=models.CharField(help_text='e.g. फेब्रुअरी २५, २०२६', max_length=100),
        ),
        migrations.AlterField(
            model_name='noticepage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media'),
        ),
    ]
