# Generated by Django 4.2.16 on 2026-02-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_options', '0002_alter_notice_date_text_ne_alter_noticepage_og_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeCTAProxy',
        ),
        migrations.DeleteModel(
            name='NoticeManagementProxy',
        ),
        migrations.AlterModelOptions(
            name='noticecategory',
            options={'ordering': ['order'], 'verbose_name': '03: Notice Categories', 'verbose_name_plural': '03: Notice Categories'},
        ),
        migrations.AlterModelOptions(
            name='noticepage',
            options={'verbose_name': '04: Notices Management', 'verbose_name_plural': '04: Notices Management'},
        ),
    ]
