# Generated by Django 6.0.2 on 2026-02-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommitteePage',
        ),
    ]
