# Generated by Django 6.0.2 on 2026-02-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_committeepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampage',
            name='og_image',
        ),
        migrations.DeleteModel(
            name='MembershipPage',
        ),
        migrations.DeleteModel(
            name='TeamPage',
        ),
    ]
