# Generated by Django 6.0.2 on 2026-02-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_teampage_og_image_delete_membershippage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='og_image',
        ),
        migrations.DeleteModel(
            name='EventsPage',
        ),
        migrations.DeleteModel(
            name='NewsPage',
        ),
    ]
