# Generated by Django 6.0.2 on 2026-02-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_newspage_og_image_delete_eventspage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='og_image',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='GalleryPage',
        ),
    ]
