# Generated by Django 4.2.16 on 2026-02-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_gallerypage_og_image_delete_contactpage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticePage',
        ),
    ]
