# Generated by Django 6.0.2 on 2026-02-17 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'Membership Page',
                'verbose_name_plural': 'Membership Pages',
            },
        ),
        migrations.CreateModel(
            name='MembershipHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/membership/hero/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Hero Image URL (CDN)')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Hero Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Hero Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Hero Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Hero Text (NE)')),
                ('text_en', models.TextField(verbose_name='Hero Text (EN)')),
                ('text_de', models.TextField(verbose_name='Hero Text (DE)')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='membership_options.membershippage')),
            ],
            options={
                'verbose_name': 'Membership Hero',
            },
        ),
        migrations.CreateModel(
            name='MembershipFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Form Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Form Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Form Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Form Text (NE)')),
                ('text_en', models.TextField(verbose_name='Form Text (EN)')),
                ('text_de', models.TextField(verbose_name='Form Text (DE)')),
                ('success_title_ne', models.CharField(max_length=200, verbose_name='Success Title (NE)')),
                ('success_title_en', models.CharField(max_length=200, verbose_name='Success Title (EN)')),
                ('success_title_de', models.CharField(max_length=200, verbose_name='Success Title (DE)')),
                ('success_text_ne', models.TextField(verbose_name='Success Text (NE)')),
                ('success_text_en', models.TextField(verbose_name='Success Text (EN)')),
                ('success_text_de', models.TextField(verbose_name='Success Text (DE)')),
                ('label_name_ne', models.CharField(default='पूरा नाम', max_length=100)),
                ('label_name_en', models.CharField(default='Full Name', max_length=100)),
                ('label_name_de', models.CharField(default='Vollständiger Name', max_length=100)),
                ('label_email_ne', models.CharField(default='ईमेल', max_length=100)),
                ('label_email_en', models.CharField(default='Email Address', max_length=100)),
                ('label_email_de', models.CharField(default='E-Mail-Adresse', max_length=100)),
                ('label_phone_ne', models.CharField(default='फोन नम्बर', max_length=100)),
                ('label_phone_en', models.CharField(default='Phone Number', max_length=100)),
                ('label_phone_de', models.CharField(default='Telefonnummer', max_length=100)),
                ('label_address_ne', models.CharField(default='ठेगाना', max_length=100)),
                ('label_address_en', models.CharField(default='Address', max_length=100)),
                ('label_address_de', models.CharField(default='Adresse', max_length=100)),
                ('label_dob_ne', models.CharField(default='जन्म मिति', max_length=100)),
                ('label_dob_en', models.CharField(default='Date of Birth', max_length=100)),
                ('label_dob_de', models.CharField(default='Geburtsdatum', max_length=100)),
                ('label_gender_ne', models.CharField(default='लिङ्ग', max_length=100)),
                ('label_gender_en', models.CharField(default='Gender', max_length=100)),
                ('label_gender_de', models.CharField(default='Geschlecht', max_length=100)),
                ('label_experience_ne', models.CharField(default='अनुभव', max_length=100)),
                ('label_experience_en', models.CharField(default='Volleyball Experience', max_length=100)),
                ('label_experience_de', models.CharField(default='Volleyball-Erfahrung', max_length=100)),
                ('label_position_ne', models.CharField(default='खेल्ने स्थान', max_length=100)),
                ('label_position_en', models.CharField(default='Preferred Position', max_length=100)),
                ('label_position_de', models.CharField(default='Bevorzugte Position', max_length=100)),
                ('label_reason_ne', models.CharField(default='सदस्यताको कारण', max_length=100)),
                ('label_reason_en', models.CharField(default='Reason for Joining', max_length=100)),
                ('label_reason_de', models.CharField(default='Grund für den Beitritt', max_length=100)),
                ('label_submit_ne', models.CharField(default='आवेदन पठाउनुहोस्', max_length=100)),
                ('label_submit_en', models.CharField(default='Submit Application', max_length=100)),
                ('label_submit_de', models.CharField(default='Antrag absenden', max_length=100)),
                ('options_gender_ne', models.CharField(default='पुरुष, महिला, अन्य', max_length=500)),
                ('options_gender_en', models.CharField(default='Male, Female, Other', max_length=500)),
                ('options_gender_de', models.CharField(default='Männlich, Weiblich, Andere', max_length=500)),
                ('options_experience_ne', models.CharField(default='शुरुआती, मध्यवर्ती, उन्नत', max_length=500)),
                ('options_experience_en', models.CharField(default='Beginner, Intermediate, Advanced', max_length=500)),
                ('options_experience_de', models.CharField(default='Anfänger, Fortgeschritten, Profi', max_length=500)),
                ('options_position_ne', models.CharField(default='सेटर, आउटसाइड हिटर, मिडल ब्लकर, लिबरो, राइट हिटर', max_length=500)),
                ('options_position_en', models.CharField(default='Setter, Outside Hitter, Middle Blocker, Libero, Right Hitter', max_length=500)),
                ('options_position_de', models.CharField(default='Zuspieler, Außenangreifer, Mittelblocker, Libero, Diagonalangreifer', max_length=500)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_settings', to='membership_options.membershippage')),
            ],
            options={
                'verbose_name': 'Form Settings & Labels',
            },
        ),
        migrations.CreateModel(
            name='MembershipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_de', models.CharField(max_length=200)),
                ('desc_ne', models.TextField()),
                ('desc_en', models.TextField()),
                ('desc_de', models.TextField()),
                ('icon', models.CharField(default='CheckCircle', help_text='Lucide icon name (e.g. Users, Award, Heart)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='membership_options.membershippage')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MembershipBenefitsProxy',
            fields=[
            ],
            options={
                'verbose_name': '03: Benefits Section',
                'verbose_name_plural': '03: Benefits Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership_options.membershippage',),
        ),
        migrations.CreateModel(
            name='MembershipFormProxy',
            fields=[
            ],
            options={
                'verbose_name': '04: Form & Labels',
                'verbose_name_plural': '04: Form & Labels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership_options.membershippage',),
        ),
        migrations.CreateModel(
            name='MembershipHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': '02: Hero Section',
                'verbose_name_plural': '02: Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership_options.membershippage',),
        ),
        migrations.CreateModel(
            name='MembershipPageProxy',
            fields=[
            ],
            options={
                'verbose_name': '01: Main Settings',
                'verbose_name_plural': '01: Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('membership_options.membershippage',),
        ),
    ]
