# Generated by Django 6.0.2 on 2026-02-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('position', models.CharField(choices=[('setter', 'Setter'), ('outside_hitter', 'Outside Hitter'), ('middle_blocker', 'Middle Blocker'), ('libero', 'Libero'), ('right_hitter', 'Right Hitter')], max_length=30)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Application',
                'verbose_name_plural': 'Membership Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
