# Generated by Django 6.0.2 on 2026-03-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_options', '0002_membershipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='bank_voucher',
            field=models.ImageField(blank=True, null=True, upload_to='images/membership/vouchers/'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='category',
            field=models.CharField(choices=[('committee', 'Committee'), ('player', 'Player')], default='player', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='label_category_de',
            field=models.CharField(default='Mitgliedschaftskategorie', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='label_category_en',
            field=models.CharField(default='Membership Category', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='label_category_ne',
            field=models.CharField(default='सदस्यता प्रकार', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='label_voucher_de',
            field=models.CharField(default='Bankbeleg Foto', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='label_voucher_en',
            field=models.CharField(default='Bank Voucher Photo', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='label_voucher_ne',
            field=models.CharField(default='बैंक भौचर फोटो', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='options_category_de',
            field=models.CharField(default='Ausschuss, Spieler', max_length=500),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='options_category_en',
            field=models.CharField(default='Committee, Player', max_length=500),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='options_category_ne',
            field=models.CharField(default='सदस्य, खेलाडी', max_length=500),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='position',
            field=models.CharField(blank=True, choices=[('setter', 'Setter'), ('outside_hitter', 'Outside Hitter'), ('middle_blocker', 'Middle Blocker'), ('libero', 'Libero'), ('right_hitter', 'Right Hitter')], max_length=30, null=True),
        ),
    ]
