# Generated by Django 6.0.2 on 2026-03-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_options', '0003_membershipapplication_bank_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='duration_years',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='last_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='parent_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='membership_options.membershipapplication'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='label_duration_de',
            field=models.CharField(default='Dauer der Mitgliedschaft (Jahre)', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='label_duration_en',
            field=models.CharField(default='Membership Duration (Years)', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='label_duration_ne',
            field=models.CharField(default='सदस्यता अवधि (वर्ष)', max_length=100),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='options_duration_de',
            field=models.CharField(default='1, 2, 5', max_length=500),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='options_duration_en',
            field=models.CharField(default='1, 2, 5', max_length=500),
        ),
        migrations.AddField(
            model_name='membershipformsettings',
            name='options_duration_ne',
            field=models.CharField(default='१, २, ५', max_length=500),
        ),
    ]
