# Generated by Django 6.0.2 on 2026-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_options', '0005_transfer_membership_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='is_approved',
        ),
    ]
