# Generated by Django 6.0.2 on 2026-02-17 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title_ne', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (NE)')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (EN)')),
                ('meta_title_de', models.CharField(blank=True, max_length=200, verbose_name='Meta Title (DE)')),
                ('meta_description_ne', models.TextField(blank=True, verbose_name='Meta Description (NE)')),
                ('meta_description_en', models.TextField(blank=True, verbose_name='Meta Description (EN)')),
                ('meta_description_de', models.TextField(blank=True, verbose_name='Meta Description (DE)')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated', max_length=500)),
                ('og_title_ne', models.CharField(blank=True, max_length=200)),
                ('og_title_en', models.CharField(blank=True, max_length=200)),
                ('og_title_de', models.CharField(blank=True, max_length=200)),
                ('og_description_ne', models.TextField(blank=True)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_de', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_og_image', to='media.media')),
            ],
            options={
                'verbose_name': 'Team Page',
                'verbose_name_plural': 'Team Pages',
            },
        ),
        migrations.CreateModel(
            name='TeamHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/team/hero/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Hero Image URL (CDN)')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Hero Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Hero Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Hero Title (DE)')),
                ('text_ne', models.TextField(verbose_name='Hero Text (NE)')),
                ('text_en', models.TextField(verbose_name='Hero Text (EN)')),
                ('text_de', models.TextField(verbose_name='Hero Text (DE)')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='team_options.teampage')),
            ],
            options={
                'verbose_name': 'Team Hero',
            },
        ),
        migrations.CreateModel(
            name='TeamCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='CTA Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='CTA Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='CTA Title (DE)')),
                ('text_ne', models.TextField(verbose_name='CTA Text (NE)')),
                ('text_en', models.TextField(verbose_name='CTA Text (EN)')),
                ('text_de', models.TextField(verbose_name='CTA Text (DE)')),
                ('button_label_ne', models.CharField(max_length=100, verbose_name='Button Label (NE)')),
                ('button_label_en', models.CharField(max_length=100, verbose_name='Button Label (EN)')),
                ('button_label_de', models.CharField(max_length=100, verbose_name='Button Label (DE)')),
                ('button_link', models.CharField(default='/membership', max_length=200)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='team_options.teampage')),
            ],
            options={
                'verbose_name': 'Team CTA',
            },
        ),
        migrations.CreateModel(
            name='TeamCoachesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Coaches Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Coaches Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Coaches Title (DE)')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches_settings', to='team_options.teampage')),
            ],
            options={
                'verbose_name': 'Coaches Section Settings',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(default='', max_length=200, verbose_name='Name (NE)')),
                ('name_en', models.CharField(default='', max_length=200, verbose_name='Name (EN)')),
                ('name_de', models.CharField(default='', max_length=200, verbose_name='Name (DE)')),
                ('number', models.CharField(max_length=10)),
                ('position_ne', models.CharField(max_length=100, verbose_name='Position (NE)')),
                ('position_en', models.CharField(max_length=100, verbose_name='Position (EN)')),
                ('position_de', models.CharField(max_length=100, verbose_name='Position (DE)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/team/players/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL (CDN)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team_options.teampage')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ne', models.CharField(default='', max_length=200, verbose_name='Name (NE)')),
                ('name_en', models.CharField(default='', max_length=200, verbose_name='Name (EN)')),
                ('name_de', models.CharField(default='', max_length=200, verbose_name='Name (DE)')),
                ('role_ne', models.CharField(max_length=200, verbose_name='Role (NE)')),
                ('role_en', models.CharField(max_length=200, verbose_name='Role (EN)')),
                ('role_de', models.CharField(max_length=200, verbose_name='Role (DE)')),
                ('experience_ne', models.CharField(max_length=200, verbose_name='Experience (NE)')),
                ('experience_en', models.CharField(max_length=200, verbose_name='Experience (EN)')),
                ('experience_de', models.CharField(max_length=200, verbose_name='Experience (DE)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/team/coaches/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL (CDN)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='team_options.teampage')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamCoachesProxy',
            fields=[
            ],
            options={
                'verbose_name': '03: Coaches Section',
                'verbose_name_plural': '03: Coaches Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('team_options.teampage',),
        ),
        migrations.CreateModel(
            name='TeamHeroProxy',
            fields=[
            ],
            options={
                'verbose_name': '02: Hero Section',
                'verbose_name_plural': '02: Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('team_options.teampage',),
        ),
        migrations.CreateModel(
            name='TeamPageProxy',
            fields=[
            ],
            options={
                'verbose_name': '01: Main Settings',
                'verbose_name_plural': '01: Main Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('team_options.teampage',),
        ),
        migrations.CreateModel(
            name='TeamPhotoCTAProxy',
            fields=[
            ],
            options={
                'verbose_name': '05: Photo & CTA Section',
                'verbose_name_plural': '05: Photo & CTA Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('team_options.teampage',),
        ),
        migrations.CreateModel(
            name='TeamPlayersProxy',
            fields=[
            ],
            options={
                'verbose_name': '04: Players Section',
                'verbose_name_plural': '04: Players Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('team_options.teampage',),
        ),
        migrations.CreateModel(
            name='TeamPhotoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Photo Section Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Photo Section Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Photo Section Title (DE)')),
                ('subtitle_ne', models.CharField(max_length=200, verbose_name='Photo Section Subtitle (NE)')),
                ('subtitle_en', models.CharField(max_length=200, verbose_name='Photo Section Subtitle (EN)')),
                ('subtitle_de', models.CharField(max_length=200, verbose_name='Photo Section Subtitle (DE)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/team/photo/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Team Photo URL (CDN)')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_section', to='team_options.teampage')),
            ],
            options={
                'verbose_name': 'Team Photo Section',
            },
        ),
        migrations.CreateModel(
            name='TeamPlayersSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ne', models.CharField(max_length=200, verbose_name='Players Title (NE)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Players Title (EN)')),
                ('title_de', models.CharField(max_length=200, verbose_name='Players Title (DE)')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_settings', to='team_options.teampage')),
            ],
            options={
                'verbose_name': 'Players Section Settings',
            },
        ),
    ]
