# Generated by Django 6.0.2 on 2026-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(default=False, verbose_name='Is Captain'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_vice_captain',
            field=models.BooleanField(default=False, verbose_name='Is Vice Captain'),
        ),
    ]
